manifestSchema = 3
sourceRoots = ["examples", "ffi_c_interop"]

[language]
version = "0.8.0-alpha.1"

[package]
name = "dev.eidos.tutorial"
version = "0.1.0"

[dependencies]
std = "0.8.0-alpha.1"

[ffi]
libraries = ["raylib", "snake_shim"]
